#!/bin/bash
# Copyright (C) 2015 James Murphy
# Licensed under the terms of the GNU GPL v2 only.
#
# Display script to read .i3text files in a directory.
# Intended to be signal triggered by the youtubed script.
#
# Left click to trigger download of video from your clipboard.
# Right click to cancel download of video from your clipboard.
# If already running, left clicking will gracefully restart youtube-dl
# and resume the download.
# Handles multiple downloads simultaneously, just copy URL, click, copy URL,
# click.
#
# Your ~/.config/i3blocks/config:
#
# [youtubed_controller]
# command=$SCRIPT_DIR/youtubed_controller DAEMON_DIR
# interval=once
# signal=1

DAEMON_DIR=${1:-"$XDG_RUNTIME_DIR"/"youtubed"}
FIFO="$DAEMON_DIR"/"youtubed.fifo"

shopt -s nullglob

BAD_SETUP=1
if [ -d "$DAEMON_DIR" ]; then
    PIDS=$(pgrep youtubed)
    dpid=$(cat "$DAEMON_DIR"/"youtubed.dpid" 2>/dev/null)
    for pid in $PIDS; do
        [ "$pid" == "$dpid" ] && BAD_SETUP=0
    done
fi

if [ "$BAD_SETUP" == "1" ]; then
    echo "<span color='red'>No youtubed running in $DAEMON_DIR</span>"
    echo "<span color='red'>No youtubed running in $DAEMON_DIR</span>"
    exit 0
fi

FULL_TEXT=""
SHORT_TEXT=""
SEPARATOR="|"
STATUS_STR="[DL]"

function send_command {
    if [ ! -p "$FIFO" ]; then
        echo "<span color='red'>fifo not found: $FIFO</span>"
        echo "<span color='red'>fifo not found: $FIFO</span>"
        exit 0
    fi

    echo "$1" > "$FIFO"
}

case "$BLOCK_BUTTON" in
    1) send_command download ;;
    3) send_command cancel ;;
    4) send_command toggle_quality ;;
esac

function append_to_with_sep {
    local TEXT="$2"
    local TO_APPEND="$1"
    if [ -n "$TEXT" ]; then
        TEXT="$TEXT $SEPARATOR $TO_APPEND"
    else
        TEXT="$TO_APPEND"
    fi
    echo "$TEXT"
}

for f in "$DAEMON_DIR"/*.i3text; do
    TEXT=$(head -n 1 "$f")
    FULL_TEXT=$(append_to_with_sep "$TEXT" "$FULL_TEXT")

    STEXT=$(tail -n 1 "$f")
    SHORT_TEXT=$(append_to_with_sep "$STEXT" "$SHORT_TEXT")
done

FULL_TEXT=$(append_to_with_sep "$STATUS_STR" "$FULL_TEXT")
SHORT_TEXT=$(append_to_with_sep "$STATUS_STR" "$SHORT_TEXT")

echo "$FULL_TEXT"
echo "$SHORT_TEXT"
exit 0
